version: "3.7"

services: 
  cinema:
    build: ./cinema
    environment: 
      MONGODB_HOST: cinema-bdd
      MONGODB_PORT: 27017
    ports:
      - 8080:80
  tickets:
    build: ./tickets
    environment: 
      CINEMA_PORT: 80
      CINEMA_HOST: cinema
    ports:
      - 8081:80

  cinema-bdd:
    image: mongo
  
  gateway:
    image: devopsfaith/krakend
    ports:
      - 80:8080
    volumes: 
      - ./krakend/:/etc/krakend/
  
  
  